server:
  port: 1501

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:1015/eureka}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      discovery:
        locator:
          enable: true
      routes:

        - id: ms-auth-service
          uri: lb://ms-auth-service
          predicates:
            - Path=/auth/**

        - id: ms-categoria-service
          uri: lb://ms-categoria-service
          predicates:
            - Path=/categoria/**

        - id: ms-producto-service
          uri: lb://ms-producto-service
          predicates:
            - Path=/producto/**